#!/usr/bin/env bash
#installing nginx
sudo apt -y update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
