#!/usr/bin/env bash=
# Install nginx web server and redirect
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
    }' /etc/nginx/sites-available/default
sudo service nginx restart

