#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine to
# 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
sudo sed -i "/listen \[\:\:\]\:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com permanent;\n\n error_page 404 /404.html;\nlocation = /404.html { root /var/www/html; internal; }\n\n" /etc/nginx/sites-available/default
sudo service nginx start
