#!/usr/bin/env bash
#create a file and contains its own pid
touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
trap hate SIGTERM
trap love SIGINT
trap del SIGQUIT

hate()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
love()
{
	echo "Y U no love me?!"
}
del()
{
	rm /var/run/myscript.pid
	exit
}
while :
do
	echo "To infinity and beyond"
	sleep 2
done
