#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
k=1
while (( "$k" <= 10 ))
do
        if (( "$k" == 4 ))
        then
                echo "bad luck"
	elif (( "$k" == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((k++))
done
