#!/usr/bin/env bash
# Gracefully reloads Gunicorn.
systemctl list-units --type service --all | awk '$1 ~ /.+\.service/ && system("systemctl is-active "$1" | grep -q active") {print $1}' | xargs -I {} systemctl reload {}
